"""Turn Python back into ``.pya`` assembly.

This closes the loop: ``pyasm dis script.py`` produces a file that
``pyasm run`` accepts, so a program can be round-tripped through assembly.
"""

from __future__ import annotations

import dis
from dataclasses import dataclass, field
from types import CodeType
from typing import Optional

from .errors import PyAsmError

__all__ = [
    "DisassemblyResult",
    "disassemble",
    "disassemble_file",
    "disassemble_source",
]


@dataclass(slots=True)
class DisassemblyResult:
    """Generated ``.pya`` text plus anything that could not be represented."""

    text: str
    warnings: list[str] = field(default_factory=list)


def disassemble(code: CodeType, *, offsets: bool = True) -> DisassemblyResult:
    """Render one code object as ``.pya`` text."""
    lines: list[str] = []
    warnings: list[str] = []
    last_line: Optional[int] = None

    for instruction in dis.get_instructions(code):
        if isinstance(instruction.argval, CodeType):
            warnings.append(
                f"{instruction.opname} at offset {instruction.offset} "
                f"references the nested code object "
                f"{instruction.argval.co_name!r}, which cannot be "
                "assembled from text"
            )
        lineno = getattr(instruction, "line_number", None)
        if lineno is not None and lineno != last_line:
            if lines:
                lines.append("")
            line_field = f"{lineno:>4}"
            last_line = lineno
        else:
            line_field = "    "

        label = getattr(instruction, "label", None)
        marker = f"L{label}:" if label is not None else ""
        label_field = f"{marker:>5}"
        offset_field = f"{instruction.offset:>5}" if offsets else ""
        body = f"{instruction.opname:<26}"
        if instruction.arg is not None:
            body += f" {instruction.arg:>4}"
        if instruction.argrepr:
            body = f"{body:<32} ({instruction.argrepr})"
        row = f"{line_field} {label_field} {offset_field}  {body}"
        lines.append(row.rstrip())

    header = [
        f"# Disassembly of {code.co_name!r}"
        + (f" from {code.co_filename}" if code.co_filename else ""),
        "# Generated by PyAsm; assemble it back with 'pyasm run'.",
        "",
    ]
    return DisassemblyResult("\n".join(header + lines) + "\n", warnings)


def disassemble_source(
    source: str, filename: str = "<string>", *, offsets: bool = True
) -> DisassemblyResult:
    """Compile ``source`` as a module and disassemble the result."""
    try:
        code = compile(source, filename, "exec")
    except SyntaxError as exc:
        raise PyAsmError(f"{filename}: {exc.msg} (line {exc.lineno})") from exc
    return disassemble(code, offsets=offsets)


def disassemble_file(path: str, *, offsets: bool = True) -> DisassemblyResult:
    """Disassemble a ``.py`` file from disk."""
    with open(path, "r", encoding="utf-8") as handle:
        return disassemble_source(handle.read(), path, offsets=offsets)
